---
resources:
- name: src
  type: git
  source:
    uri: https://github.com/openregister/registers-cli.git
    branch: master

- name: ecr
  type: docker-image
  source:
    repository: ((readonly_private_ecr_repo_url))
    tag: registers-cli

jobs:
  - name: build
    plan:
      - get: src
        trigger: true
      - put: ecr
        params: { build: src }
