---
resources:
- name: src
  type: git
  source:
    uri: https://github.com/openregister/registry-data.git
    branch: master
    paths:
    - rsf/((register-name)).rsf

- name: src-rs
  type: git
  source:
    uri: https://github.com/openregister/route-service.git
    branch: develop # FIXME

- name: govuk-paas
  type: cf
  source:
    api: https://api.london.cloud.service.gov.uk
    organization: gds-registers
    space: ((paas-space))
    username: ((paas-user))
    password: ((paas-password))

jobs:
- name: build
  plan:
  - get: src
    trigger: true

  - task: build-paas-app
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((readonly_private_ecr_repo_url))
          tag: registers-cli
      inputs:
      - name: src
      outputs:
      - name: build
      params:
        RSF_FILE: rsf/((register-name)).rsf
      run:
        path: registers
        args: [ "build", "--target", "cloudfoundry", "src/rsf/((register-name)).rsf" ]

  - task: soft-store-build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/cf-cli
          tag: "21e5ddc4c7265b112cbeb0993b0915fa9366a876"
      inputs:
      - name: build
      outputs:
      - name: src
      run:
        path: sh
        args:
        - -euc
        - |
          mv ./build ./src/

- name: deploy
  plan:
  - get: src
    trigger: true
    passed: ["build"]
  - get: src-rs
    trigger: true

  - task: setup-space
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/cf-cli
          tag: "21e5ddc4c7265b112cbeb0993b0915fa9366a876"
      params:
        USERNAME: ((paas-user))
        PASSWORD: ((paas-password))
        API: https://api.london.cloud.service.gov.uk
        ORGANIZATION: gds-registers
        SPACE: ((paas-space))
      run:
        path: sh
        args:
        - -euc
        - |
          cf login -a "${API}" -u "${USERNAME}" -p "${PASSWORD}" -o "${ORGANIZATION}"

          cf create-space "${SPACE}"

  - put: govuk-paas
    params:
      manifest: build/((register-name))/manifest.yml
      show_app_log: true
      path: build/((register-name))
      current_app_name: ((register-name))-app

  - put: govuk-paas
    params:
      manifest: src-rs/manifest.yml
      show_app_log: true
      path: build/((register-name))
      current_app_name: ((register-name))-route-service

  - task: create-cdn
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/cf-cli
          tag: "21e5ddc4c7265b112cbeb0993b0915fa9366a876"
      params:
        REGISTER: ((register-name))
        USERNAME: ((paas-user))
        PASSWORD: ((paas-password))
        API: https://api.london.cloud.service.gov.uk
        ORGANIZATION: gds-registers
        SPACE: ((paas-space))
        DATA_BLOB: '{"domain": "${REGISTER}.register.gov.uk,www.${REGISTER}.register.gov.uk"}'
      run:
        path: sh
        args:
        - -euc
        - |
          cf login -a "${API}" -u "${USERNAME}" -p "${PASSWORD}" -o "${ORGANIZATION}" -s "${SPACE}"

          cf create-domain "${ORGANIZATION}" "${REGISTER}.register.gov.uk"

          cf create-service cdn-route cdn-route "${REGISTER}-cdn" -c "${DATA_BLOB}" || cf update-service "${REGISTER}-cdn" -c "${DATA_BLOB}"

          cf service "${REGISTER}-cdn"

  - task: bind-routing
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: governmentpaas/cf-cli
          tag: "21e5ddc4c7265b112cbeb0993b0915fa9366a876"
      params:
        REGISTER: ((register-name))
        USERNAME: ((paas-user))
        PASSWORD: ((paas-password))
        API: https://api.london.cloud.service.gov.uk
        ORGANIZATION: gds-registers
        SPACE: ((paas-space))
      run:
        path: sh
        args:
        - -euc
        - |
          cf login -a "${API}" -u "${USERNAME}" -p "${PASSWORD}" -o "${ORGANIZATION}" -s "${SPACE}"

          cf create-user-provided-service "${REGISTER}-binding" -r "${REGISTER}-route-service.cloudapps.digital"

          cf bind-route-service "${REGISTER}.register.gov.uk" "${REGISTER}-binding" --hostname "${REGISTER}-app"
