---
resources:
- name: registry-data-git
  type: git
  source:
    uri: https://github.com/openregister/registry-data.git
    branch: master
    paths:
    - rsf/((register-name)).rsf

- name: route-service-git
  type: git
  source:
    uri: https://github.com/openregister/route-service.git
    branch: develop # FIXME

- name: govuk-paas
  type: cf
  source:
    api: https://api.london.cloud.service.gov.uk
    organization: gds-registers
    space: ((paas-space))
    username: ((paas-user))
    password: ((paas-password))

- name: cf-cli
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: "21e5ddc4c7265b112cbeb0993b0915fa9366a876"

jobs:
- name: deploy
  plan:
  - get: registry-data-git
    trigger: true

  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((readonly_private_ecr_repo_url))
          tag: registers-cli
      inputs:
      - name: registry-data-git
      outputs:
      - name: build
      run:
        path: registers
        args: [ "build", "--target", "cloudfoundry", "registry-data-git/rsf/((register-name)).rsf" ]

  - get: cf-cli

  - task: create-space
    image: cf-cli
    config:
      platform: linux
      params: &cfparams
        USERNAME: ((paas-user))
        PASSWORD: ((paas-password))
        API: https://api.london.cloud.service.gov.uk
        ORGANIZATION: gds-registers
        SPACE: ((paas-space))
        REGISTER: ((register-name))
      run:
        path: sh
        args:
        - -euc
        - |
          cf login -a "${API}" -u "${USERNAME}" -p "${PASSWORD}" -o "${ORGANIZATION}" -s sandbox
          cf create-space "${SPACE}"

  - put: govuk-paas
    params:
      manifest: build/((register-name))/manifest.yml
      show_app_log: true
      path: build/((register-name))
      current_app_name: ((register-name))-app

  - get: route-service-git
    trigger: true

  - put: govuk-paas
    params:
      manifest: route-service-git/manifest.yaml
      show_app_log: true
      path: route-service-git
      current_app_name: ((register-name))-route-service

  - task: attach-domain
    image: cf-cli
    config:
      platform: linux
      params:
        <<: *cfparams
      run:
        path: sh
        args:
        - -euc
        - |
          DATA_BLOB="{\"domain\": \"${REGISTER}.register.gov.uk,www.${REGISTER}.register.gov.uk\"}"
          cf login -a "${API}" -u "${USERNAME}" -p "${PASSWORD}" -o "${ORGANIZATION}" -s "${SPACE}"
          cf domains | grep -q "register.gov.uk" || cf create-domain "${ORGANIZATION}" "register.gov.uk"
          cf create-service cdn-route cdn-route "${REGISTER}-cdn" -c "${DATA_BLOB}" || cf update-service "${REGISTER}-cdn" -c "${DATA_BLOB}"
          echo "======================================"
          cf service "${REGISTER}-cdn"
          echo "======================================"
          cf service "${REGISTER}-binding" || cf create-user-provided-service "${REGISTER}-binding" -r "https://${REGISTER}-route-service.london.cloudapps.digital"
          echo "FIXME: this is invalid domain, need to make it good"
          cf bind-route-service "london.cloudapps.digital" "${REGISTER}-binding" --hostname "${REGISTER}-app"
