---
resource_types:
- name: cf-cli-resource
  type: docker-image
  source:
    repository: nulldriver/cf-cli-resource
    tag: latest

resources:
- name: registry-data-git
  type: git
  source:
    uri: https://github.com/openregister/registry-data.git
    branch: master
    paths:
    - rsf/((register-name)).rsf

- name: route-service-git
  type: git
  source:
    uri: https://github.com/openregister/route-service.git
    branch: master

- name: registers-cli-image
  type: docker-image
  source:
    repository: ((readonly_private_ecr_repo_url))
    tag: registers-cli

- name: conformance-test-image
  type: docker-image
  source:
    repository: ((readonly_private_ecr_repo_url))
    tag: conformance-test

- name: cf-paas
  type: cf-cli-resource
  source:
    api: https://api.london.cloud.service.gov.uk
    org: gds-registers
    username: ((paas-user))
    password: ((paas-password))

jobs:
- name: deploy-app
  plan:
  - get: registry-data-git
    trigger: true

  - get: registers-cli-image
    trigger: true

  - task: build-register
    image: registers-cli-image
    config:
      platform: linux
      inputs:
      - name: registry-data-git
      outputs:
      - name: build
      run:
        path: registers
        args: [ "build", "--target", "cloudfoundry", "registry-data-git/rsf/((register-name)).rsf" ]

  - put: paas-space
    resource: cf-paas
    params:
      command: create-space
      space: ((register-name))

  - put: paas-app
    resource: cf-paas
    params:
      command: push
      space: ((register-name))
      app_name: app
      hostname: ((register-name))-app
      manifest: build/((register-name))/manifest.yml
      path: build/((register-name))

- name: deploy-route-service
  plan:
  - get: route-service-git
    trigger: true

  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.12-stretch
      inputs:
        - name: route-service-git
      run:
        dir: route-service-git
        path: go
        args: [ "test", "./..." ]

  - put: paas-space
    resource: cf-paas
    params:
      command: create-space
      space: ((register-name))

  - put: paas-route-service
    resource: cf-paas
    params:
      command: push
      space: ((register-name))
      app_name: route-service
      hostname: ((register-name))-rs
      manifest: route-service-git/manifest.yaml
      path: route-service-git

- name: attach-domain
  plan:
  - get: cf-paas
    passed: [ deploy-app, deploy-route-service ]
    trigger: true

  - put: bind-route-service
    resource: cf-paas
    params:
      commands:
      - command: create-user-provided-service
        space: ((register-name))
        service_instance: route-service-binding
        route_service_url: https://((register-name))-rs.london.cloudapps.digital
      - command: bind-route-service
        space: ((register-name))
        service_instance: route-service-binding
        domain: london.cloudapps.digital
        hostname: ((register-name))-app

- name: conformance-test
  plan:
    - get: cf-paas
      passed: [ attach-domain ]
      trigger: true
    - get: conformance-test-image
      trigger: true
    - task: run-test
      image: conformance-test-image
      config:
        platform: linux
        run:
          path: /app/openregister-conformance
          args: [ "--api-version", "1", "--register", "((register-name))", "--register-domain", "((domain))", "https://((register-name))-app.((domain))" ]
