---
resources:
- name: registry-data-git
  type: git
  source:
    uri: https://github.com/openregister/registry-data.git
    branch: master
    paths:
    - rsf/((register-name)).rsf

- name: route-service-git
  type: git
  source:
    uri: https://github.com/openregister/route-service.git
    branch: master

templates:
  config: &cf-task
    platform: linux
    image_resource:
      type: docker-image
      source:
        repository: governmentpaas/cf-cli
        tag: "21e5ddc4c7265b112cbeb0993b0915fa9366a876"
    params:
      USERNAME: ((paas-user))
      PASSWORD: ((paas-password))
      API: https://api.london.cloud.service.gov.uk
      ORGANIZATION: gds-registers
      SPACE: ((paas-space))
      REGISTER: ((register-name))

jobs:
- name: deploy-app
  plan:
  - get: registry-data-git
    trigger: true

  - task: build-register
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((readonly_private_ecr_repo_url))
          tag: registers-cli
      inputs:
      - name: registry-data-git
      outputs:
      - name: build
      run:
        path: registers
        args: [ "build", "--target", "cloudfoundry", "registry-data-git/rsf/((register-name)).rsf" ]

  - task: push-app
    config:
      <<: *cf-task
      inputs:
        - name: build
      run:
        path: sh
        args:
        - -euc
        - |
          cf login -a "${API}" -u "${USERNAME}" -p "${PASSWORD}" -o "${ORGANIZATION}" -s sandbox
          cf create-space "${SPACE}"
          cf target -s "${SPACE}"
          cf push app -f "build/${REGISTER}/manifest.yml" -p "build/${REGISTER}" --no-route

- name: deploy-route-service
  plan:
  - get: route-service-git
    trigger: true

  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.12-stretch
      inputs:
        - name: route-service-git
      run:
        dir: route-service-git
        path: go
        args: [ "test", "./..." ]

  - task: deploy-route-service
    config:
      <<: *cf-task
      inputs:
        - name: route-service-git
      run:
        path: sh
        args:
        - -euc
        - |
          cf login -a "${API}" -u "${USERNAME}" -p "${PASSWORD}" -o "${ORGANIZATION}" -s sandbox
          cf create-space "${SPACE}"
          cf target -s "${SPACE}"
          cf push route-service -f route-service-git/manifest.yaml -p route-service-git --no-route

  - task: attach-domain
    config:
      <<: *cf-task
      run:
        path: sh
        args:
        - -euc
        - |
          cf login -a "${API}" -u "${USERNAME}" -p "${PASSWORD}" -o "${ORGANIZATION}" -s "${SPACE}"
          cf map-route app london.cloudapps.digital --hostname "${REGISTER}-app"
          cf map-route route-service london.cloudapps.digital --hostname "${REGISTER}-rs"
          cf service route-service-binding || cf create-user-provided-service route-service-binding -r "https://${REGISTER}-rs.london.cloudapps.digital"
          cf bind-route-service london.cloudapps.digital route-service-binding --hostname "${REGISTER}-app"
