---
resource_types:
- name: concourse-pipeline
  type: docker-image
  source: { repository: concourse/concourse-pipeline-resource }

resources:
- name: registry-data-git
  type: git
  source:
    uri: https://github.com/openregister/registry-data.git
    branch: master
    paths:
    - "rsf/*.rsf"

- name: pipelines-git
  type: git
  source:
    uri: https://github.com/openregister/pipelines.git
    branch: master

- name: deploy-pipelines
  type: concourse-pipeline
  source:
    teams:
      - name: register
        username: register
        password: ((readonly_local_user_password))

jobs:
- name: update-deploy-pipelines
  plan:
  - get: registry-data-git
    trigger: true

  - get: pipelines-git
    trigger: true

  - task: set-pipelines
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: ruby }
      inputs:
        - name: registry-data-git
        - name: pipelines-git
      outputs:
        - name: pipelines-config
      params:
        REGISTRY_DATA: registry-data-git/rsf/*.rsf
        OUTPUT: pipelines-config/config.yaml
        DEPLOY_CONFIG_FILE: pipelines-git/deploy.yaml
        UNPAUSED: false
        DOMAIN: london.cloudapps.digital
      run:
        path: pipelines-git/generate_pipelines.rb

  - put: deploy-pipelines
    params:
      pipelines_file: pipelines-config/config.yaml

- name: update-other-pipelines
  plan:
  - get: pipelines-git
    trigger: true
  - put: deploy-pipelines
    params:
      pipelines:
        - name: update-pipelines
          config_file: pipelines-git/update-pipelines.yaml
          team: register
  - put: deploy-pipelines
    params:
      pipelines:
        - name: build-cli
          config_file: pipelines-git/build-cli.yaml
          team: register
  - put: deploy-pipelines
    params:
      pipelines:
        - name: build-tests
          config_file: pipelines-git/build-tests.yaml
          team: register
